### ISSUE TITLE
Is source.deployment unused?

### ISSUE THREAD

**Issue by craigfurman** [concourse/bosh-deployment-resource#19]
I've only had a quick glance, but it looks unused. If so, can it be removed from readme?

**Comment by xoebus** [comment]
It's used here: https://github.com/concourse/bosh-deployment-resource/blob/master/lib/bosh_deployment_resource/out_command.rb#L66-L69

**Comment by craigfurman** [comment]
It's unclear to me why the resource would bother checking that?

**Comment by vito** [comment]
@craigfurman it happens to not technically require it now; we have later features planned to support e.g. triggering when a deployment changes and fetching metadata from the target deployment.

as it stands right now it's just to ensure people are using it as a one-to-one mapping to a single deployment, rather than a bag of configuration, so that when we add these features things'll "just work".

**Comment by craigfurman** [comment]
hi again, we are trying to create dynamically-named bosh deployments in our pipeline, and are getting stopped by this deployment name checking.

Have you got any recent thoughts on this feature?
